//* Coder: NGUYEN DOAN CHI THUC - HUYNH VAN DAT
//* Date of writing code: 29/11/2021
//* Class: IT16301
package com.software.ui;

import com.software.dao.NhanVienDAO;
import com.software.dao.TaiKhoanDAO;
import com.software.entity.NhanVien;
import com.software.jdbcHelper.MsgBox;
import com.software.jdbcHelper.XImage;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author DELL
 */
public class ChangePassDialog extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordDialog
     */
    int demPass = 0, demConfirm = 0;
    int clickFirstPass = 0, clickFirstConfirm = 0;

    public ChangePassDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblTitle.requestFocus();
        pwdPass.setBackground(new java.awt.Color(0, 0, 1, 0));
        pwdConfirm.setBackground(new java.awt.Color(0, 0, 1, 0));
        this.setIconImage(XImage.getAppIcon());
        pwdPass.setEchoChar((char) 0);
        pwdConfirm.setEchoChar((char) 0);
    }

    public void clickPasswordField(int click, JPasswordField PwField, JLabel lblLabel, int index) {
        if (click == 0) {
            PwField.setText("");
            lblLabel.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/hidden.png")));
            lblLabel.setEnabled(true);
            PwField.setEchoChar('●');
            index = 0;
        }
        click++;
    }

    public void clickHide(JPasswordField PwField, JLabel lblLabel, int index, String chuoi) {
        if (!PwField.getText().equals(chuoi)) {
            if (index % 2 != 0) {
                lblLabel.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/hidden.png")));
                PwField.setEchoChar('●');
            } else {
                lblLabel.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/view.png")));
                PwField.setEchoChar((char) 0);
            }
            index++;
        }
    }

    public boolean CheckForm() {
        String isPassWord = "^.{8,}";
        boolean check = true;
        if (pwdPass.getText().isEmpty() || pwdPass.getText().equals("Mật Khẩu")) {
            MsgBox.alert(this, "Vui lòng nhập mật khẩu!");
            check = false;
        } else if (pwdConfirm.getText().isEmpty() || pwdConfirm.getText().equals("Xác Nhận Mật Khẩu")) {
            MsgBox.alert(this, "Vui lòng xác nhận mật khẩu!");
            check = false;
        } else if (!pwdPass.getText().matches(isPassWord)) {
            MsgBox.alert(this, "Mật khẩu không hợp lệ!\nMật khẩu ít nhất 8 ký tự");
            check = false;
        } else if (!pwdConfirm.getText().equals(pwdPass.getText())) {
            MsgBox.alert(this, "Xác nhận mật khẩu không đúng\nVui lòng kiểm tra lại!");
            check = false;
        }
        return check;
    }

    public void UpdatePass() {
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();
        NhanVienDAO nvDAO = new NhanVienDAO();
        List<NhanVien> listNV = nvDAO.SelectAll();
        String soDienThoai = null;
        for (int i = 0; i < listNV.size(); i++) {
            if (ForgotPasswordDialog.mailTo.equals(listNV.get(i).getGmail())) {
                soDienThoai = listNV.get(i).getSoDienThoai();
                break;
            }
        }
        tkDAO.updatePass(pwdPass.getText(), soDienThoai);
        MsgBox.alert(this, "Đổi mật khẩu thành công!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLoiPass = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblConfirmPass = new javax.swing.JLabel();
        pwdPass = new javax.swing.JPasswordField();
        lblAnHienPass = new javax.swing.JLabel();
        lblAnHienConfirm = new javax.swing.JLabel();
        pwdConfirm = new javax.swing.JPasswordField();
        lblLoiConfirm = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 102, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CHANGE PASSWORD");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 500, 40));

        jPanel1.setOpaque(false);

        lblLoiPass.setForeground(new java.awt.Color(255, 0, 0));

        lblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/smartphone.png"))); // NOI18N

        lblConfirmPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/confirmPass.png"))); // NOI18N

        pwdPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pwdPass.setForeground(new java.awt.Color(102, 102, 255));
        pwdPass.setText("Mật Khẩu");
        pwdPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 51, 255)));
        pwdPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPassFocusLost(evt);
            }
        });
        pwdPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdPassMouseClicked(evt);
            }
        });

        lblAnHienPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnHienPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/view.png"))); // NOI18N
        lblAnHienPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 51, 255)));
        lblAnHienPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnHienPassMouseClicked(evt);
            }
        });

        lblAnHienConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnHienConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/view.png"))); // NOI18N
        lblAnHienConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 51, 255)));
        lblAnHienConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnHienConfirmMouseClicked(evt);
            }
        });

        pwdConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pwdConfirm.setForeground(new java.awt.Color(102, 102, 255));
        pwdConfirm.setText("Xác Nhận Mật Khẩu");
        pwdConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(0, 51, 255)));
        pwdConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdConfirmFocusLost(evt);
            }
        });
        pwdConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdConfirmMouseClicked(evt);
            }
        });

        lblLoiConfirm.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdPass, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(lblLoiPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(lblAnHienPass, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(lblLoiConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(lblAnHienConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblLoiPass, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdPass)
                    .addComponent(lblAnHienPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoiConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pwdConfirm)
                        .addComponent(lblAnHienConfirm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 500, 130));

        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/back.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 36, 36));

        lblConfirm.setBackground(new java.awt.Color(51, 102, 255));
        lblConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirm.setText("CONFIRM");
        lblConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirm.setOpaque(true);
        lblConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmMouseExited(evt);
            }
        });
        getContentPane().add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 220, 120, 43));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        lblNen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/background.jpg"))); // NOI18N
        getContentPane().add(lblNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseClicked
        if (CheckForm() == true) {
            this.UpdatePass();
            this.dispose();
            new LoginDialog().setVisible(true);
        }
    }//GEN-LAST:event_lblConfirmMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        new ForgotPasswordDialog().setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/closeHower.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/close.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseEntered
        lblConfirm.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(51, 255, 51)));
    }//GEN-LAST:event_lblConfirmMouseEntered

    private void lblConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseExited
        lblConfirm.setBorder(null);
    }//GEN-LAST:event_lblConfirmMouseExited

    private void pwdPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusGained
        this.clickPasswordField(clickFirstPass, pwdPass, lblAnHienPass, demPass);
        if (pwdPass.getText().equals("Mật Khẩu")) {
            pwdPass.setText(null);
        }
    }//GEN-LAST:event_pwdPassFocusGained

    private void pwdPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdPassMouseClicked
        this.clickPasswordField(clickFirstPass, pwdPass, lblAnHienPass, demPass);
    }//GEN-LAST:event_pwdPassMouseClicked

    private void pwdConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdConfirmMouseClicked
        this.clickPasswordField(clickFirstConfirm, pwdConfirm, lblAnHienConfirm, demConfirm);
    }//GEN-LAST:event_pwdConfirmMouseClicked

    private void pwdPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPassFocusLost
        if (pwdPass.getText().isEmpty()) {
            pwdPass.setText("Mật Khẩu");
            lblAnHienPass.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/view.png")));
            pwdPass.setEchoChar((char) 0);
            demPass = 0;
            clickFirstPass = 0;
        }
    }//GEN-LAST:event_pwdPassFocusLost

    private void pwdConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmFocusGained
        this.clickPasswordField(clickFirstConfirm, pwdConfirm, lblAnHienConfirm, demConfirm);
        if (pwdConfirm.getText().equals("Nhập Lại Pass")) {
            pwdConfirm.setText(null);
        }
    }//GEN-LAST:event_pwdConfirmFocusGained

    private void pwdConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmFocusLost
        if (pwdConfirm.getText().isEmpty()) {
            pwdConfirm.setText("Nhập Lại Pass");
            lblAnHienConfirm.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/view.png")));
            pwdConfirm.setEchoChar((char) 0);
            demConfirm = 0;
            clickFirstConfirm = 0;
        }
    }//GEN-LAST:event_pwdConfirmFocusLost

    private void lblAnHienPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnHienPassMouseClicked
        this.clickHide(pwdPass, lblAnHienPass, demPass, "Mật Khẩu");
    }//GEN-LAST:event_lblAnHienPassMouseClicked

    private void lblAnHienConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnHienConfirmMouseClicked
        this.clickHide(pwdConfirm, lblAnHienConfirm, demConfirm, "Xác Nhận Mật Khẩu");
    }//GEN-LAST:event_lblAnHienConfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChangePassDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnHienConfirm;
    private javax.swing.JLabel lblAnHienPass;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblConfirmPass;
    private javax.swing.JLabel lblLoiConfirm;
    private javax.swing.JLabel lblLoiPass;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField pwdConfirm;
    private javax.swing.JPasswordField pwdPass;
    // End of variables declaration//GEN-END:variables
}
