//* Coder: NGUYEN DOAN CHI THUC
//* Date of writing code: 29/11/2021
//* MSSV: PC01573
//* Class: IT16301
package com.software.ui;

import com.software.jdbcHelper.MailSender;
import com.software.jdbcHelper.MsgBox;
import com.software.jdbcHelper.XImage;
import static com.software.ui.ForgotPasswordDialog.randomInt;
import java.awt.Color;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class OTPDialog extends javax.swing.JFrame {

    int second = 60;
    Timer timer;

    public OTPDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblTitle.requestFocus();
        this.setIconImage(XImage.getAppIcon());
        setTime();
    }

    @SuppressWarnings({"UseSpecificCatch", "CallToPrintStackTrace"})
    public void GuiMail() {
        for (int i = 1; i < 2; i++) {
            double randomDouble = Math.random();
            randomDouble = randomDouble * 1000000 + 1;
            randomInt = (int) randomDouble;
        }
        try {
            String taiKhoan = "hotroshopbingbong@gmail.com";
            String matKhau = "Bingbong123@";

            Properties prop = new Properties();
            prop.put("mail.smtp.host", "smtp.gmail.com");
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.enable", "true");

            Session session = Session.getDefaultInstance(prop, new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(taiKhoan, matKhau);
                }
            });

            String from = "hotroshopbingbong@gmail.com";
            String to = ForgotPasswordDialog.mailTo;
            String subject = "Mã xác nhận Bing Bong Shop ";
            String body = "Mã xác nhận của bạn là : " + randomInt;

            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(to)
            );
            message.setSubject(subject);
            message.setText(body);
            MailSender.queue(message);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    public void setTime() {
        timer = new Timer(1000, (e) -> {
            second--;
            lblTime.setText("00:" + String.valueOf(second));
            if (second == 0) {
                ForgotPasswordDialog.randomInt = 0;
                lblTime.setText("Mã xác nhận đã hết hiệu lực!");
                timer.stop();
            }
        });
        timer.start();
    }

    boolean checkCode() {
        try {
            String code = txtNumber1.getText() + txtNumber2.getText() + txtNumber3.getText() + txtNumber4.getText() + txtNumber5.getText() + txtNumber6.getText();
            if (Integer.valueOf(code) != ForgotPasswordDialog.randomInt) {
                MsgBox.alert(this, "Mã xác nhận chưa chính xác vui lòng kiểm tra lại!!!");
                return false;
            } else if (code.isEmpty()) {
                MsgBox.alert(this, "Vui lòng nhập mã xác thực!!!");
                return false;
            }
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Mã xác nhận chưa chính xác vui lòng kiểm tra lại!!!");
            return false;
        }
        return true;
    }

    public void PasteCode(JTextField txtOne, JTextField txtTwo) {
        if (txtOne.getText().length() == 1) {
            txtOne.nextFocus();
            txtTwo.requestFocus();
        } else if (txtOne.getText().length() > 1) {
            int index1 = txtOne.getText().charAt(0);
            char kiTu = (char) index1;
            txtOne.setText("");
            txtOne.setText(String.valueOf(kiTu));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfirm = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNumber1 = new javax.swing.JTextField();
        txtNumber2 = new javax.swing.JTextField();
        txtNumber3 = new javax.swing.JTextField();
        txtNumber4 = new javax.swing.JTextField();
        txtNumber5 = new javax.swing.JTextField();
        txtNumber6 = new javax.swing.JTextField();
        lblResendCode = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfirm.setBackground(new java.awt.Color(51, 102, 255));
        lblConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConfirm.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirm.setText("CONFIRM");
        lblConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConfirm.setOpaque(true);
        lblConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConfirmMouseExited(evt);
            }
        });
        getContentPane().add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 220, 120, 43));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/back.png"))); // NOI18N
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 36, 36));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 102, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Auth Code");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 36));

        jPanel1.setOpaque(false);

        txtNumber1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber1.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber1KeyReleased(evt);
            }
        });

        txtNumber2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber2.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber2KeyReleased(evt);
            }
        });

        txtNumber3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber3.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber3KeyReleased(evt);
            }
        });

        txtNumber4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber4.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber4KeyReleased(evt);
            }
        });

        txtNumber5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber5.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber5KeyReleased(evt);
            }
        });

        txtNumber6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNumber6.setForeground(new java.awt.Color(102, 102, 255));
        txtNumber6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumber6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumber6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, -1));

        lblResendCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResendCode.setForeground(new java.awt.Color(102, 102, 102));
        lblResendCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResendCode.setText("Resend Code");
        lblResendCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblResendCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResendCodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResendCodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResendCodeMouseExited(evt);
            }
        });
        getContentPane().add(lblResendCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, 29));

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 0, 0));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("00:00");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 500, 29));

        lblNen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/background.jpg"))); // NOI18N
        getContentPane().add(lblNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.dispose();
        new ForgotPasswordDialog().setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseClicked
        if (checkCode()) {
            this.dispose();
            new ChangePassDialog().setVisible(true);
        }
    }//GEN-LAST:event_lblConfirmMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/closeHower.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/close.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblConfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseEntered
        lblConfirm.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(51, 255, 51)));
    }//GEN-LAST:event_lblConfirmMouseEntered

    private void lblConfirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseExited
        lblConfirm.setBorder(null);
    }//GEN-LAST:event_lblConfirmMouseExited

    private void lblResendCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResendCodeMouseEntered
        lblResendCode.setForeground(new Color(0, 102, 0));
        lblResendCode.setText("<html><u>Resend Code</u></html>");
    }//GEN-LAST:event_lblResendCodeMouseEntered

    private void lblResendCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResendCodeMouseExited
        lblResendCode.setForeground(new Color(102, 102, 102));
        lblResendCode.setText("Resend Code");
    }//GEN-LAST:event_lblResendCodeMouseExited

    private void txtNumber1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber1KeyReleased
        if (txtNumber1.getText().trim().length() == 6) {
            int index1 = txtNumber1.getText().trim().charAt(0);
            int index2 = txtNumber1.getText().trim().charAt(1);
            int index3 = txtNumber1.getText().trim().charAt(2);
            int index4 = txtNumber1.getText().trim().charAt(3);
            int index5 = txtNumber1.getText().trim().charAt(4);
            int index6 = txtNumber1.getText().trim().charAt(5);
            char kiTu1 = (char) index1;
            char kiTu2 = (char) index2;
            char kiTu3 = (char) index3;
            char kiTu4 = (char) index4;
            char kiTu5 = (char) index5;
            char kiTu6 = (char) index6;
            txtNumber1.setText("");
            txtNumber2.setText("");
            txtNumber3.setText("");
            txtNumber4.setText("");
            txtNumber5.setText("");
            txtNumber6.setText("");
            txtNumber1.setText(String.valueOf(kiTu1));
            txtNumber2.setText(String.valueOf(kiTu2));
            txtNumber3.setText(String.valueOf(kiTu3));
            txtNumber4.setText(String.valueOf(kiTu4));
            txtNumber5.setText(String.valueOf(kiTu5));
            txtNumber6.setText(String.valueOf(kiTu6));
            lblConfirm.requestFocus();
            return;
        }
        this.PasteCode(txtNumber1, txtNumber2);
    }//GEN-LAST:event_txtNumber1KeyReleased

    private void txtNumber2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber2KeyReleased
        this.PasteCode(txtNumber2, txtNumber3);
    }//GEN-LAST:event_txtNumber2KeyReleased

    private void txtNumber3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber3KeyReleased
        this.PasteCode(txtNumber3, txtNumber4);
    }//GEN-LAST:event_txtNumber3KeyReleased

    private void txtNumber4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber4KeyReleased
        this.PasteCode(txtNumber4, txtNumber5);
    }//GEN-LAST:event_txtNumber4KeyReleased

    private void txtNumber5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber5KeyReleased
        this.PasteCode(txtNumber5, txtNumber6);
    }//GEN-LAST:event_txtNumber5KeyReleased

    private void txtNumber6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumber6KeyReleased
        this.PasteCode(txtNumber6, txtNumber6);
        lblConfirm.requestFocus();
    }//GEN-LAST:event_txtNumber6KeyReleased

    private void lblResendCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResendCodeMouseClicked
        timer.stop();
        second = 60;
        GuiMail();
        setTime();
    }//GEN-LAST:event_lblResendCodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OTPDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblNen;
    private javax.swing.JLabel lblResendCode;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    private javax.swing.JTextField txtNumber3;
    private javax.swing.JTextField txtNumber4;
    private javax.swing.JTextField txtNumber5;
    private javax.swing.JTextField txtNumber6;
    // End of variables declaration//GEN-END:variables
}
