/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.software.ui;

import com.software.dao.DoanhThuDAO;
import com.software.jdbcHelper.MsgBox;
import com.software.jdbcHelper.XImage;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class XemDoanhThu extends javax.swing.JFrame {

    /**
     * Creates new form xemDoanhThu
     */
    public XemDoanhThu() {
        initComponents();
        this.setTitle("Shop Thể Thao BingBong");
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(XImage.getAppIcon());
    }

    public boolean KiemTraNgay() {
        if (txtNBD.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập ngày bắt đầu!!!");
            txtNBD.requestFocus();
            return false;
        } else if (txtNKT.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập ngày kết thúc!!!");
            txtNKT.requestFocus();
            return false;
        }
        DateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        sdf.setLenient(false);
        try {
            String date1 = txtNBD.getText().replace("/", "-");
            String date2 = date1.replace(".", "-");
            sdf.parse(date2);
        } catch (ParseException e) {
            MsgBox.alert(this, "Ngày bắt đầu không hợp lệ!\nVui lòng nhập ngày theo định dạng dd-MM-YYYY!");
            txtNBD.requestFocus();
            return false;
        }
        try {
            String date1 = txtNKT.getText().replace("/", "-");
            String date2 = date1.replace(".", "-");
            sdf.parse(date2);
        } catch (ParseException e) {
            MsgBox.alert(this, "Ngày kết thúc không hợp lệ!\nVui lòng nhập ngày theo định dạng dd-MM-YYYY!");
            txtNKT.requestFocus();
            return false;
        }
        return true;
    }

    public String ChuyenNgay(JTextField txtField, String dinhDangBegin, String dinhDangEnd) throws ParseException {
        String dateBD1 = txtField.getText().replace("/", "-");
        String dateBD2 = dateBD1.replace(".", "-");
        Date date = new SimpleDateFormat("dd-MM-yyyy").parse(dateBD2);
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        String kq = f.format(date);
        return kq;
    }

    public void fillTableDiemChuyenDe() throws ParseException {
        DoanhThuDAO daoDT = new DoanhThuDAO();
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);
        String ngayBD = ChuyenNgay(txtNBD, "dd-MM-yyyy", "yyyy-MM-dd");
        String ngayKT = ChuyenNgay(txtNKT, "dd-MM-yyyy", "yyyy-MM-dd");
        List<Object[]> list = daoDT.getDoanhThu(ngayBD, ngayKT);
        for (Object[] row : list) {
            model.addRow(new Object[]{row[0], row[1], row[2]});
        }
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(localeVN);
        tblDoanhThu.setValueAt(currencyFormat.format(tblDoanhThu.getValueAt(0, 0)), 0, 0);
        tblDoanhThu.setValueAt(currencyFormat.format(tblDoanhThu.getValueAt(0, 1)), 0, 1);
        tblDoanhThu.setValueAt(currencyFormat.format(tblDoanhThu.getValueAt(0, 2)), 0, 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        btnXemDT = new javax.swing.JButton();
        lblTitleHD2 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        txtNBD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNKT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        btnXemDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemDT.setText("Xem doanh Thu");
        btnXemDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDTActionPerformed(evt);
            }
        });
        getContentPane().add(btnXemDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        lblTitleHD2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleHD2.setForeground(new java.awt.Color(153, 0, 0));
        lblTitleHD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleHD2.setText("XEM DOANH THU BÁN HÀNG");
        getContentPane().add(lblTitleHD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 726, -1));

        tblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        tblDoanhThu.setForeground(new java.awt.Color(204, 0, 0));
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tổng Tiền Bán Được", "Tổng giá giảm", "Doanh Thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThu.setRowHeight(70);
        jScrollPane17.setViewportView(tblDoanhThu);

        getContentPane().add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 220, 700, 114));
        getContentPane().add(txtNBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 91, 249, 38));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ngày Bắt đầu:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 91, 112, 38));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ngày Kết thúc");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 150, 112, 38));
        getContentPane().add(txtNKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 150, 249, 37));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/software/icon/background3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDTActionPerformed
        if (KiemTraNgay() == true) {
            try {
                fillTableDiemChuyenDe();
            } catch (ParseException ex) {
                Logger.getLogger(XemDoanhThu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXemDTActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/closeHower.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new ImageIcon(getClass().getResource("/com/software/icon/close.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemDoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblTitleHD2;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTextField txtNBD;
    private javax.swing.JTextField txtNKT;
    // End of variables declaration//GEN-END:variables
}
